wget https://www.argentina.gob.ar/coronavirus/preguntasfrecuentes
wget https://www.argentina.gob.ar/salud/coronavirus-COVID-19
wget https://www.argentina.gob.ar/coronavirus/cuidarnos
wget https://www.argentina.gob.ar/salud/coronavirus/poblacion
wget https://www.argentina.gob.ar/salud/coronavirus/poblacion/prevencion
wget https://www.argentina.gob.ar/salud/coronavirus/poblacion/mayores
wget https://www.argentina.gob.ar/salud/coronavirus/poblacion/viajeros
wget https://www.argentina.gob.ar/salud/coronavirus/poblacion/aislamiento-sanitario
wget https://www.argentina.gob.ar/salud/coronavirus/poblacion/escuelas
wget https://www.argentina.gob.ar/coronavirus/medidas-gobierno
wget https://www.argentina.gob.ar/coronavirus/aislamiento
wget https://www.argentina.gob.ar/coronavirus/aislamiento/motivo
wget https://www.argentina.gob.ar/coronavirus/aislamiento/exceptuados
wget https://www.argentina.gob.ar/coronavirus/aislamiento/recomendaciones
wget https://www.argentina.gob.ar/coronavirus/dnu
wget https://www.argentina.gob.ar/coronavirus/telefonos
wget https://www.argentina.gob.ar/salud/coronavirus-COVID-19/plan-operativo
wget https://www.argentina.gob.ar/coronavirus/zonas-transmision-local
wget http://www.msal.gob.ar/index.php?filter_problematica=92&filter_soporte=0&palabra_clave=&option=com_ryc_contenidos
